### ISSUE TITLE
Rewrite GraphicsPage::OnMouseMove() to refresh the display correctly

### ISSUE THREAD

**Issue by vadz** [esternin/eXtrema#27]
This function is the last one to use `wxClientDC` and it does it with `wxINVERT` logical mode which doesn't work at all in GTK 3, so it has to be fixed by deleting the last object and adding the new one.

My main problem is that I don't really understand when this code is used, i.e. what do I need to do to test it. I'll try to understand this later, but if you already know, please tell me, TIA!

**Comment by esternin** [comment]
I think this has been fixed by [this merge](https://github.com/esternin/eXtrema/commit/7ff5a7867dadca1d8a7377bb698ec3f679b18947), closing the issue.
