### ISSUE TITLE
Collision between different files on case-insensitive filesystems

### ISSUE THREAD

**Issue by vadz** [esternin/eXtrema#41]
Cloning Extrema repository under MSW results in
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Help/Characteristics/Characteristics.htm'
  'Help/Characteristics/characteristics.htm'
```

I think adding both files in d3b407585258dc7a82400b466e3a06253e26307a was just a mistake and one of them should be removed, but I don't know which one, so I'd rather leave actually doing this to you.

**Comment by esternin** [comment]
An old structured Help file removed (https://github.com/esternin/eXtrema/commit/c9eb90161b269dd1f685073d38b01ed181849d41)
