### ISSUE TITLE
Not all UTF-16 characters are correctly rendered on screen

### ISSUE THREAD

**Issue by esternin** [esternin/eXtrema#50]
This affects "PERP" 0x27C2, "LANGLE" 0x27E8 and "RANGLE" 0x27E9 only, and on Windows only.  The codes are correct and the characters are present in FreeFont family (checked with gucharmap), and EPS is correctly rendered, but on screen those three are not recognized, seemingly in all fonts.

This is a known bug in 4.7.0 release.

**Comment by vadz** [comment]
FWIW I don't see U+27C2, U+27E8 or U+27E9 in FreeSans font downloaded from http://ftp.gnu.org/gnu/freefont/freefont-ttf-20120503.zip

**Comment by esternin** [comment]
How can this be? 

![image](https://user-images.githubusercontent.com/29458452/134076114-8ebba468-42d0-4281-80b7-86656e79e4b1.png)

**Comment by esternin** [comment]
I found alternative glyphs for the three characters, these are not as "correct" as the ones I used so far, but it works around this issue:
```
PERP = 0x22A5 ("UP TACK")
LANGLE = 0x2329 ("LEFT-POINTING ANGLE BRACKET")
RANGLE = 0x232A ("RIGHT-POINTING ANGLE BRACKET")
```
With these, both Linux and Win versions seem to work fine on screen.

**Comment by vadz** [comment]
> How can this be?

I honestly have no idea, but Windows charmap.exe doesn't show any characters assigned to this range.

The most likely explanation is that we're using different fonts, but I thought you used the official upstream versions. If not, what's the canonical source for them?

**Comment by esternin** [comment]
I may not have turned off showing glyphs from all fonts, and misinterpreted what gucharmap was showing me.  The above alternative glyphs seem perfectly adequate.

The canonical form is the one I link to, as far as I can tell.  I even loaded the .zip fonts (the Windows package) and replaced the ones that came with the Ubuntu package, and did not see any difference.

**Comment by esternin** [comment]
Since I kept PostScript character names unchanged, and "correct", I do not think any changes anywhere else (like `GRA_postscript.cpp`) are needed.

Closing the issue.
