### ISSUE TITLE
XNUMBERHEIGHT, YNUMBERHEIGHT not recognised

### ISSUE THREAD

**Issue by fboseglav** [esternin/eXtrema#62]
In Linux RHEL7 and Xubuntu, the XNUMBERHEIGHT and %XNUMBERHEIGHT keywords are documented in the help menu and included in some examples but raise an error:

SET: unknown keyword: XNUMBERHEIGHT
The following line caused the error:
set xnumberheight 2.5

The same applies to the y-axis keywords. XNUMBERSHEIGHT, etc seem to work as expected, however selecting the keyword in the Index list of the help menu raises an error in W10 and Linux, i.e.:

Unable to open requested HTML document: file:///tmp/.mount_extremqbHM6m/usr/local/share/extrema/Help/Characteristics/xnumberheight.htm

This error also occurs for several other keywords such as XNUMBERSANGLE, XNUMBERSON, ...

**Comment by esternin** [comment]
commit 7ec238a fixes typo in three help files: NUMBERHEIGHT --> NUMBERSHEIGHT, no functional changes are needed. Seems to fix the links as well, as these are generated automatically from the corrected strings, and the file `/Help/Characteristics/xnumbersheight.htm` already exists and in place.

Closing as resolved.
