### ISSUE TITLE
fit command causes crash

### ISSUE THREAD

**Issue by fboseglav** [esternin/eXtrema#63]
Extrema 4.7.2: checked with some Linux versions, RHEL7 and Xubuntu, if the dependent variable is omitted from the fit command, i.e. fit A+B*x rather than fit y=A+B*x, eXtrema crashes without warning.

In W10, the same opens a pop-up window that displays an "Unhandled exception occurred" error and forces a program exit if the user selects 'abort' or crashes if the user attempts a 'retry'. However, selecting 'ignore' gives control back to the user.

Perhaps this error message window could be included in the Linux versions?

**Comment by esternin** [comment]
Thanks, Phil, good catch.

The syntax is supposed to be `fit <vector> = [ <fit_expression> ]` where a  `<fit_expression>` is optional if there was one previously used.  The interpreter had some trouble in cases where `=` was missing, as it could not differentiate lhs from rhs.  Commit 997da5b is a quick fix, not thoroughly tested.  I added a pop-up warning that should at least prevent outright crashes.

The Windows version was relying on the OS-level traps to prevent crashes, eXtrema itself was, indeed, having address exceptions at the same point.  Hopefully, my fix will also work there, as we should never rely on the OS to save us from our own faults.

Needs testing. The same issue may need looking at in `bestfit` and possibly some other commands.

**Comment by esternin** [comment]
To test:
```
x=[1:10]
generate\random y -1 1 10
y=y+x**2
scalar\vary z
fit y=x**z

=`this should work normally, since a previous rhs can be used, should yield z=2`
fit y=
=`this should complain`
fit y
=`this should also work, using x=x**z, yielding z=1`
fit x=
```

**Comment by esternin** [comment]
`bestfit` is not affected.  Testing shows reasonably robust behaviour in case of syntax errors (missing `=`). 

Closing as resolved.
