### ISSUE TITLE
Compiling under gcc 13 needs a change to `#include ...`

### ISSUE THREAD

**Issue by cvoinf** [esternin/eXtrema#72]
Compiling extrema on Linux-Manjaro resulted in:

```
In file included from ../../src/Graphics/GRA_drawableText.cpp:43:
../../src/Graphics/GRA_specialCharacters.h:25:5: error: 'uint32_t' does not name a type
   25 |     uint32_t const ucode; // Unicode character code
      |     ^~~~~~~~
../../src/Graphics/GRA_specialCharacters.h:1:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  +++ |+#include <cstdint>
    1 | /*
../../src/Graphics/GRA_drawableText.cpp:165:3: error: no matching function for call to 'std::vector<GRA_specialCharacter>::vector(<brace-enclosed initializer list>)'
  165 |   };
      |   ^

``` 

As suggested, I added `#include <cstdint>` in `src/Graphics/GRA_specialCharacters.h` and everything compiled perfectly.

**Comment by esternin** [comment]
Could you report the compiler version you are using, please.

**Comment by cvoinf** [comment]
g++ (GCC) 13.2.1 20230801
GNU ld (GNU Binutils) 2.42.0
GNU Make 4.4.1
Autoconf 2.72
uname -m = x86_64
uname -r = 6.6.19-1-MANJARO
uname -s = Linux

**Comment by esternin** [comment]
This seems specifically a [gcc v.13 issue](https://gcc.gnu.org/gcc-13/porting_to.html).  I am surprised that this is the only thing that showed up with this gcc upgrade, given that:

> Header dependency changes
> 
> Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without including the right headers will no longer compile.
> 
> The following headers are used less widely in libstdc++ and may need to be included explicitly when compiling with GCC 13:
> ```
>     <string> (for std::string, std::to_string, std::stoi etc.)
>     <system_error> (for std::error_code, std::error_category, std::system_error).
>     <cstdint> (for std::int8_t, std::int32_t etc.)
>     <cstdio> (for std::printf, std::fopen etc.)
>     <cstdlib> (for std::strtol, std::malloc etc.)
> ```

Your fix `#include <cstdint>` would fail under v.12, which is what the current version under LTS Debian is. I am reluctant to add a gcc-version-related exception, unless someone knows of a clean way of doing that.

**Comment by vadz** [comment]
No, including `<cstdint>` wouldn't fail with gcc 12, why do you think it would? It always was the correct thing to do, it just worked without it now but no longer does.

**Comment by esternin** [comment]
> No, including `<cstdint>` wouldn't fail with gcc 12, why do you think it would? It always was the correct thing to do, it just worked without it now but no longer does.

Ah, I stand corrected.  My mistake was to look for `cstdint.h`, while the include is actually of the `cstdint`.

Well, then we can add this to the file in question.  Like I said, I am surprised it's only the one file that needs that. Unless you are planning to make the corresponding change in `wx/wx.h` ?

**Comment by esternin** [comment]
How about [this commit](https://github.com/esternin/eXtrema/commit/fd1aa317f95446dec19712a93a0da9d31fe02973) ?

**Comment by vadz** [comment]
There is no need to change `wx/wx.h` because it doesn't use `uint32_t` nor any other types defined in `cstdint`. But any file using them should include this header.

**Comment by esternin** [comment]
closing with https://github.com/esternin/eXtrema/commit/6c2febdb89ba6ee68464d2cc86889b230101e59d
